### ISSUE TITLE
LLVM Support

### ISSUE THREAD

**Issue by Lichtso** [michaeljclark/riscv-probe#4]
Hi, I thought it would be nice to have examples of RISC-V being compiled and linked using LLVM additionally to the GNU toolchain.

https://github.com/Lichtso/riscv-llvm-templates

I don't want to merge them, but maybe we can reference each other with a link in the README.

**Comment by michaeljclark** [comment]
Oh cool. I noticed you have rv8 support.

Reminds me that I need to spend some time at some point to upgrade rv8 to privileged ISA v1.10.

If you want to make a pull request against the README, please go ahead, otherwise, I can just go ahead add references with a link to riscv-llvm-templates.

Thanks.

**Comment by Lichtso** [comment]
Yes, please go ahead.
